/**
 * Generates src/data/eu-ai-act-index.js — a lightweight metadata module
 * (no article/recital body text) used by the app shell: route parsing, SEO
 * meta, breadcrumbs, prev/next nav, and the sidebar tree.
 *
 * The full ~600KB EU_AI_ACT_DATA module is now only imported by the lazy
 * per-view components (ArticleDetail, ThemeView, SearchResults, AnnexView,
 * EnhancedRecitalsTab, ChatPanel, …), so the home/timeline/fria/role/blog
 * pages no longer download it on initial load.
 *
 * Run automatically as the first step of `npm run build`. Regenerate manually
 * with `npm run gen:index` after editing eu-ai-act-data.js or annexes.js.
 */
import { writeFileSync } from "fs";
import { EU_AI_ACT_DATA } from "../src/data/eu-ai-act-data.js";
import { ANNEXES } from "../src/data/annexes.js";

const ARTICLE_INDEX = {};
for (const [key, a] of Object.entries(EU_AI_ACT_DATA.articles)) {
  ARTICLE_INDEX[key] = { number: a.number, title: a.title, chapter: a.chapter, themes: a.themes || [] };
}

const RECITAL_NUMBERS = Object.values(EU_AI_ACT_DATA.recitals)
  .map((r) => r.number)
  .sort((x, y) => x - y);

const ANNEX_INDEX = ANNEXES.map((a) => ({ id: a.id, number: a.number, title: a.title, summary: a.summary }));

const out = `// AUTO-GENERATED by scripts/gen-index.mjs — do not edit by hand.
// Lightweight EU AI Act metadata (no article/recital body text) for the app
// shell (routing, SEO, sidebar tree). Keeps the ~600KB data module off the
// initial-load path. Regenerate with: npm run gen:index
export const METADATA = ${JSON.stringify(EU_AI_ACT_DATA.metadata)};
export const CHAPTERS = ${JSON.stringify(EU_AI_ACT_DATA.chapters)};
export const THEMES = ${JSON.stringify(EU_AI_ACT_DATA.themes)};
export const ARTICLE_INDEX = ${JSON.stringify(ARTICLE_INDEX)};
export const RECITAL_NUMBERS = ${JSON.stringify(RECITAL_NUMBERS)};
export const ANNEX_INDEX = ${JSON.stringify(ANNEX_INDEX)};
`;

const target = new URL("../src/data/eu-ai-act-index.js", import.meta.url);
writeFileSync(target, out);
console.log(`Generated src/data/eu-ai-act-index.js (${(out.length / 1024).toFixed(1)} KB)`);
